// const pal = require('./palette')
// const blockSet = new Set()
//
//
//
// for (let i of pal){
//   if(i.name.indexOf('element') === -1 && i.name.indexOf('sign') === -1 && i.name.indexOf('portal') === -1 && i.name.indexOf('rail') === -1 && i.name.indexOf('button') === -1 && i.name.indexOf('door') === -1){
//     blockSet.add(i.name.replace('minecraft:',''))
//   }
// }
// console.log(blockSet,blockSet.size)
module.exports = [
  'stone',
  'gravel',
  'oak_stairs',
  // 'acacia_fence_gate',
  'vine',
  'gold_block',
  'stone_slab4',
  'trapped_chest',
  'grass',
  'blue_ice',
  'bedrock',
  'planks',
  // 'barrier',
  'dirt',
  'scaffolding',
  // 'beetroot',
  'beacon',
  'soul_sand',
  'diamond_block',
  'coal_ore',
  // 'fire',
  'log2',
  'cobblestone',
  // 'flowing_water',
  'stone_slab',
  // 'lava',
  'stonebrick',
  // 'sapling',
  // 'wheat',
  'diamond_ore',
  'coal_block',
  'brick_block',
  'wool',
  'sandstone',
  // 'water',
  'red_glazed_terracotta',
  // 'skull',
  'brown_mushroom',
  // 'flowing_lava',
  'concretePowder',
  'furnace',
  'sand',
  'diorite_stairs',
  'gold_ore',
  'iron_ore',
  'dark_prismarine_stairs',
  'web',
  'log',
  'leaves',
  'sponge',
  'monster_egg',
  // 'glass',
  'lapis_ore',
  'bookshelf',
  'lapis_block',
  'dispenser',
  // 'pistonArmCollision',
  'noteblock',
  // 'bed',
  'sticky_piston',
  // 'tallgrass',
  'jukebox',
  // 'deadbush',
  'piston',
  'obsidian',
  // 'yellow_flower',
  // 'ladder',
  // 'red_flower',
  // 'red_mushroom',
  'lit_furnace',
  'iron_block',
  'double_stone_slab',
  // 'chorus_plant',
  'tnt',
  'mossy_cobblestone',
  // 'torch',
  'mob_spawner',
  'chest',
  'stone_brick_stairs',
  // 'redstone_wire',
  'crafting_table',
  'polished_andesite_stairs',
  // 'farmland',
  'undyed_shulker_box',
  'stone_stairs',
  'jungle_stairs',
  // 'lever',
  'ender_chest',
  // 'stone_pressure_plate',
  // 'wooden_pressure_plate',
  'redstone_ore',
  // 'lit_redstone_ore',
  // 'unlit_redstone_torch',
  // 'redstone_torch',
  // 'snow_layer',
  'ice',
  'snow',
  // 'cactus',
  'clay',
  // 'reeds',
  'fence',
  'pumpkin',
  'netherrack',
  'glowstone',
  'lit_pumpkin',
  // 'cake',
  'end_brick_stairs',
  // 'unpowered_repeater',
  // 'cartography_table',
  // 'powered_repeater',
  // 'invisibleBedrock',
  // 'iron_bars',
  'brown_mushroom_block',
  'red_mushroom_block',
  // 'coral',
  // 'glass_pane',
  'melon_block',
  // 'reserved6',
  'emerald_block',
  // 'pumpkin_stem',
  'seaLantern',
  // 'melon_stem',
  'fence_gate',
  'brick_stairs',
  'mycelium',
  // 'waterlily',
  // 'jungle_pressure_plate',
  'nether_brick',
  'sandstone_stairs',
  'nether_brick_fence',
  'nether_brick_stairs',
  // 'nether_wart',
  'enchanting_table',
  'red_sandstone',
  // 'brewing_stand',
  'double_stone_slab2',
  'cauldron',
  'birch_stairs',
  'end_stone',
  // 'dragon_egg',
  'redstone_lamp',
  // 'lit_redstone_lamp',
  'dropper',
  // 'cocoa',
  'emerald_ore',
  // 'tripwire_hook',
  // 'tripWire',
  'spruce_stairs',
  // 'fletching_table',
  'command_block',
  // 'cobblestone_wall',
  // 'blast_furnace',
  // 'flower_pot',
  // 'carrots',
  // 'potatoes',
  // 'anvil',
  // 'light_weighted_pressure_plate',
  // 'bamboo',
  // 'heavy_weighted_pressure_plate',
  // 'unpowered_comparator',
  // 'powered_comparator',
  // 'daylight_detector',
  'redstone_block',
  'purpur_block',
  'dark_oak_fence_gate',
  'quartz_ore',
  'hopper',
  'double_wooden_slab',
  'quartz_block',
  'quartz_stairs',
  'wooden_slab',
  'stained_hardened_clay',
  // 'stained_glass_pane',
  'leaves2',
  'acacia_stairs',
  'dark_oak_stairs',
  'slime',
  'prismarine',
  'hay_block',
  // 'carpet',
  'chain_command_block',
  'hardened_clay',
  'packed_ice',
  // 'double_plant',
  // 'standing_banner',
  'granite_stairs',
  // 'wall_banner',
  // 'daylight_detector_inverted',
  'red_sandstone_stairs',
  'stone_slab2',
  'spruce_fence_gate',
  'birch_fence_gate',
  'double_stone_slab3',
  'stripped_acacia_log',
  'jungle_fence_gate',
  'repeating_command_block',
  'grass_path',
  // 'birch_pressure_plate',
  'stripped_birch_log',
  // 'frame',
  // 'chorus_flower',
  'purpur_stairs',
  'end_bricks',
  // 'end_rod',
  // 'end_gateway',
  'magma',
  'nether_wart_block',
  'red_nether_brick',
  'bone_block',
  'shulker_box',
  'purple_glazed_terracotta',
  'white_glazed_terracotta',
  'orange_glazed_terracotta',
  'magenta_glazed_terracotta',
  'light_blue_glazed_terracotta',
  'yellow_glazed_terracotta',
  'lime_glazed_terracotta',
  'pink_glazed_terracotta',
  'gray_glazed_terracotta',
  'silver_glazed_terracotta',
  'cyan_glazed_terracotta',
  'blue_glazed_terracotta',
  'brown_glazed_terracotta',
  'green_glazed_terracotta',
  'black_glazed_terracotta',
  'concrete',
  // 'stained_glass',
  'podzol',
  'stonecutter',
  'structure_block',
  'prismarine_stairs',
  'prismarine_bricks_stairs',
  'stripped_spruce_log',
  'stripped_jungle_log',
  'stripped_dark_oak_log',
  'stripped_oak_log',
  // 'chemistry_table',
  // 'chemical_heat',
  // 'grindstone',
  'smooth_red_sandstone_stairs',
  'carved_pumpkin',
  'smooth_stone',
  // 'kelp',
  // 'coral_fan_hang',
  // 'acacia_pressure_plate',
  // 'sea_pickle',
  // 'dark_oak_pressure_plate',
  'coral_block',
  // 'coral_fan',
  // 'coral_fan_dead',
  // 'coral_fan_hang2',
  // 'coral_fan_hang3',
  'dried_kelp_block',
  // 'lava_cauldron',
  // 'seagrass',
  // 'spruce_pressure_plate',
  // 'conduit',
  // 'bubble_column',
  // 'turtle_egg',
  // 'bamboo_sapling',
  'stone_slab3',
  'double_stone_slab4',
  'andesite_stairs',
  'polished_granite_stairs',
  'normal_stone_stairs',
  'polished_diorite_stairs',
  'mossy_stone_brick_stairs',
  'smooth_sandstone_stairs',
  'mossy_cobblestone_stairs',
  'red_nether_brick_stairs',
  'smooth_quartz_stairs',
  'smoker',
  'smithing_table',
  'barrel',
  'bell',
  'lantern' ]
